# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: notifly 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "notifly"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pedro Passalini", "Rafael Carvalho"]
  s.date = "2014-11-24"
  s.description = "This project intend to offer a full notification system, back and front-end."
  s.email = ["henrique.passalini@gmail.com", "rafael@algorich.com.br"]
  s.executables = ["rails"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".editorconfig",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/images/notifly/.keep",
    "app/assets/javascripts/notifly.js",
    "app/assets/javascripts/notifly/counter.js.erb",
    "app/assets/javascripts/notifly/get_notifications.js.erb",
    "app/assets/stylesheets/notifly.css",
    "app/assets/stylesheets/notifly/layout.css",
    "app/controllers/notifly/application_controller.rb",
    "app/controllers/notifly/notifications_controller.rb",
    "app/helpers/notifly/view_helper.rb",
    "app/models/notifly/notification.rb",
    "app/views/notifly/layouts/_actions.html.erb",
    "app/views/notifly/layouts/_counter.html.erb",
    "app/views/notifly/layouts/_footer.html.erb",
    "app/views/notifly/layouts/_index.html.erb",
    "app/views/notifly/layouts/_notification.html.erb",
    "app/views/notifly/layouts/_notifly.html.erb",
    "app/views/notifly/notifications/counter.js.erb",
    "app/views/notifly/notifications/index.js.erb",
    "app/views/notifly/notifications/read_specific.js.erb",
    "app/views/notifly/notifications/toggle_read.js.erb",
    "app/views/notifly/templates/_default.html.erb",
    "bin/rails",
    "config/routes.rb",
    "db/migrate/20141103170528_create_notifly_notifications.rb",
    "db/migrate/20141104150224_add_data_to_notification.rb",
    "db/migrate/20141117193436_add_seen_to_notifly_notification.rb",
    "lib/generators/notifly/install/install_generator.rb",
    "lib/generators/notifly/install/templates/config/initializers/notifly.rb",
    "lib/generators/notifly/install/utils.rb",
    "lib/generators/notifly/views/USAGE",
    "lib/generators/notifly/views/views_generator.rb",
    "lib/notifly.rb",
    "lib/notifly/engine.rb",
    "lib/notifly/models/base.rb",
    "lib/notifly/models/flyable.rb",
    "lib/notifly/models/notifiable.rb",
    "lib/notifly/models/options/fly.rb",
    "lib/notifly/railtie.rb",
    "lib/tasks/notifly_tasks.rake",
    "spec/controllers/notifly/notifications_controller_spec.rb",
    "spec/dummy/README.rdoc",
    "spec/dummy/Rakefile",
    "spec/dummy/app/assets/images/.keep",
    "spec/dummy/app/assets/javascripts/application.js",
    "spec/dummy/app/assets/stylesheets/application.css",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/controllers/concerns/.keep",
    "spec/dummy/app/controllers/site_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/mailers/.keep",
    "spec/dummy/app/models/.keep",
    "spec/dummy/app/models/concerns/.keep",
    "spec/dummy/app/models/dummy_object.rb",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/app/views/site/index.html.erb",
    "spec/dummy/bin/bundle",
    "spec/dummy/bin/rails",
    "spec/dummy/bin/rake",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.exemple.yml",
    "spec/dummy/config/database.travis.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/assets.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/cookies_serializer.rb",
    "spec/dummy/config/initializers/filter_parameter_logging.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/initializers/wrap_parameters.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/config/secrets.yml",
    "spec/dummy/db/migrate/20141031165049_create_dummy_objects.rb",
    "spec/dummy/db/migrate/20141103191353_create_posts.rb",
    "spec/dummy/db/migrate/20141104121318_add_dummy_to_post.rb",
    "spec/dummy/db/schema.rb",
    "spec/dummy/lib/assets/.keep",
    "spec/dummy/log/.keep",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/spec/features/notifly/counter_spec.rb",
    "spec/dummy/spec/features/notifly/loading_notifications_spec.rb",
    "spec/dummy/spec/features/notifly/read_notifications_spec.rb",
    "spec/dummy/spec/models/dummy_object_spec.rb",
    "spec/dummy/spec/models/post_spec.rb",
    "spec/models/notifly/notification_spec.rb",
    "spec/rails_helper.rb",
    "spec/spec_helper.rb",
    "spec/support/shared_connection.rb",
    "spec/support/suppress_log.rb",
    "spec/support/wait_ajax.rb",
    "vendor/assets/javascripts/twitter/bootstrap.js",
    "vendor/assets/stylesheets/twitter/bootstrap.css"
  ]
  s.homepage = "https://github.com/algorich/notifly"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A full notification system"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 4"])
      s.add_runtime_dependency(%q<jquery-rails>, ["< 5", ">= 3.0"])
      s.add_runtime_dependency(%q<kaminari>, ["~> 0.16.1"])
      s.add_runtime_dependency(%q<font-awesome-rails>, ["~> 4.2.0"])
      s.add_development_dependency(%q<pg>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 3.1.0"])
      s.add_development_dependency(%q<capybara>, ["~> 2.4.4"])
      s.add_development_dependency(%q<poltergeist>, ["~> 1.5.1"])
      s.add_development_dependency(%q<shoulda-matchers>, ["~> 2.7.0"])
      s.add_development_dependency(%q<pry-rails>, [">= 0"])
      s.add_development_dependency(%q<pry-rescue>, [">= 0"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<launchy>, [">= 0"])
      s.add_development_dependency(%q<better_errors>, [">= 0"])
      s.add_development_dependency(%q<binding_of_caller>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 4"])
      s.add_dependency(%q<jquery-rails>, ["< 5", ">= 3.0"])
      s.add_dependency(%q<kaminari>, ["~> 0.16.1"])
      s.add_dependency(%q<font-awesome-rails>, ["~> 4.2.0"])
      s.add_dependency(%q<pg>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["~> 3.1.0"])
      s.add_dependency(%q<capybara>, ["~> 2.4.4"])
      s.add_dependency(%q<poltergeist>, ["~> 1.5.1"])
      s.add_dependency(%q<shoulda-matchers>, ["~> 2.7.0"])
      s.add_dependency(%q<pry-rails>, [">= 0"])
      s.add_dependency(%q<pry-rescue>, [">= 0"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<launchy>, [">= 0"])
      s.add_dependency(%q<better_errors>, [">= 0"])
      s.add_dependency(%q<binding_of_caller>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 4"])
    s.add_dependency(%q<jquery-rails>, ["< 5", ">= 3.0"])
    s.add_dependency(%q<kaminari>, ["~> 0.16.1"])
    s.add_dependency(%q<font-awesome-rails>, ["~> 4.2.0"])
    s.add_dependency(%q<pg>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["~> 3.1.0"])
    s.add_dependency(%q<capybara>, ["~> 2.4.4"])
    s.add_dependency(%q<poltergeist>, ["~> 1.5.1"])
    s.add_dependency(%q<shoulda-matchers>, ["~> 2.7.0"])
    s.add_dependency(%q<pry-rails>, [">= 0"])
    s.add_dependency(%q<pry-rescue>, [">= 0"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<launchy>, [">= 0"])
    s.add_dependency(%q<better_errors>, [">= 0"])
    s.add_dependency(%q<binding_of_caller>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

